/-
  Auto-generated by CatPrism Parser
  Source: {source_file}
  ε-Functor proof with δ = {metric}, ε = {epsilon}
-/

import Core
open CategoryTheory

namespace {namespace}

def {functor_name} : EpsFunctor (δ := {metric}) {epsilon} where
  F := {
    obj := fun X => match X with
{object_map}
    ,
    map := fun f => match f with
{morphism_map}
  }

  comp_ok := by
{proof_block}

end {namespace}
